from __future__ import annotations

import json
from typing import Any

from .schema import CAUSE_CATEGORIES

SYSTEM_PROMPT = """You are the root-cause analysis (RCA) agent for SentinelAI, a platform that
predicts and diagnoses service incidents in microservice environments. You receive a JSON
evidence package generated by the monitoring pipeline and must reason about the probable
root cause from the telemetry signals.

You MUST respond with a single JSON object and nothing else - no markdown, no commentary.
The JSON MUST match this exact schema:

{
  "probable_root_cause": "concise human-readable root cause (1-2 sentences)",
  "root_cause_category": "one of: {categories}",
  "evidence": ["each item states one concrete observation taken from the metrics deltas, top anomalous features, or correlated logs"],
  "confidence_score": 0.0,
  "recommended_action": "the single most effective next action for an on-call engineer"
}

Rules:
- "root_cause_category" must be exactly one of these values: {categories}
- "confidence_score" is a float between 0 and 1 reflecting how strongly the signals support the root cause.
- Base your diagnosis ONLY on the provided evidence; never invent telemetry that is not present.
- Prefer the most parsimonious root cause that explains the dominant anomalous signal.
""".replace("{categories}", ", ".join(CAUSE_CATEGORIES))

USER_TEMPLATE = """Here is the structured evidence package for an incident:

```json
{evidence_json}
```

Diagnose the probable root cause and return the JSON result."""


def build_rca_prompt(evidence: dict[str, Any] | str) -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for the given evidence package.

    Accepts either a dict (Evidence.asdict()-shaped) or a JSON string.
    """
    if isinstance(evidence, str):
        evidence_json = evidence
    else:
        evidence_json = json.dumps(evidence, indent=2, default=str)
    return SYSTEM_PROMPT, USER_TEMPLATE.format(evidence_json=evidence_json)


def instruction_block() -> str:
    """Return the JSON-schema contract used by the prompt (for tests/docs)."""
    return json.dumps(
        {
            "probable_root_cause": "string",
            "root_cause_category": list(CAUSE_CATEGORIES),
            "evidence": ["string"],
            "confidence_score": "float 0..1",
            "recommended_action": "string",
        },
        indent=2,
    )